---
output: html_document
editor_options: 
  chunk_output_type: console
---


# (PART\*) Illuminate {-}

# Use General Principles of High-Quality Data Viz in R {-}

In the spring of 2021, [nearly all of the American West was in a drought](https://droughtmonitor.unl.edu/DmData/TimeSeries.aspx). In April of that year, [officials in Southern California declared a water emergency](https://www.cbsnews.com/news/west-climate-change-water/), citing unprecedented conditions. 

This wouldn't have come as news to those living in California and other Western states. In addition to the direct impact of drought (leading areas of California to implement water use restrictions), people could see the indirect impact of drought in increased wildfires. With forests dried out by years of drought conditions, wildfires became more frequent, filling skies in the West with smoke. 

TODO: Add personal story

While more and more people are able to see the increase in drought conditions, communicating the extent of this change remains a challenge. How can we show the data in a way that accurately represents the data while is also compelling enough to have lay people take notice? 

This was the challenge that freelance data visualization designers Cédric Scherer and Georgios Karamanis took on in November 2021. Commissioned by the magazine Scientific American to create a data visualization that would highlight the extent to which droughts in the United States have become common, they turned to the ggplot2 package to turn what could be (pardon the pun) dry data on droughts into a set of impactful data visualizations. 

There was nothing unique about the data that Cédric and Georgios used. It was the same data from the National Drought Center that news organizations used in their stories. But what these two information designers did was present the data in a way that it both grabs attention and communicates clearly the scale of the phenomenon. 

## Close read of viz to show why it's effective

To understand why this visualization is effective, let's break it down into pieces. 

At the broadest level, what we see as a single chart is actually a set of charts. Each rectangle represents one year in one region. 

TODO: Add image

Looking at this single visualization of one year in one region, we can see that the x axis shows the week while the y axis shows the percentage of that region at different drought levels. 

TODO: Add image

The stacked bars also use color to show the different drought levels. The lightest bar shows the percentage of the region that is abnormally dry while the darkest bar shows the percentage in exceptional drought conditions. 

TODO: Add image

When I asked Cédric and Georgios to speak with me about this data visualization, they initially told me that the code for this piece might be too simple to highlight R's data viz power. No, I told them, I want to speak with you precisely *because* the code is not super complex. The fact that Cédric and Georgios were able to produce this complex graph with relatively simple code shows the power of R for data visualization. And this is made possible because of a theory called the grammar of graphics.

## The grammar of graphics

If you've used Excel to make graphs, you're probably familiar with this menu: 

TODO: Add image https://show.rfor.us/UewnER

Working in Excel, your graph-making journey begins with the step of selecting the type of graph you want to make. If you've only ever made data visualization in Excel, this first step may seem so obvious that you've never even considered conceptualizing the process of creating data visualization in any different way. This was certainly the case for me in my years as a run-of-the-mill Excel user.

But seem people think of data visualization at a much deeper level. One of these was the late statistician Leland Wilkinson. Wilkinson thought deeply for years about what data visualization is and how we can describe it. In 1999, he published a book called *The Grammar of Graphics* that sought to develop a consistent way of describing *all* graphs. [As Paul Velleman and Howard Wainer wrote in an obituary for Wilkinson](https://www.tandfonline.com/doi/full/10.1080/09332480.2022.2066422), *The Grammar of Graphics* is "not a book to curl up with in front of a fire on a cold winter’s night." They continued: "As literature, the plot is weak, but as science, the plots are better described than you’ll find anywhere else."

Wilkinson argued that we should think of plots not as distinct types a la Excel, but as following a grammar that we can use to describe *any* plot. Throughout the book that Wilkinson is best remembered for, he presented general principles to describe graphs. Just as knowledge of English grammar tells us that a noun followed by a verb ("he goes") works while the opposite ("goes he") does not, knowledge of the grammar of graphics allows us to understand why certain graph types "work." Or, as Wilkinson put it,

> A language consisting of words and no grammar (statement = word) expresses only as many ideas as there are words. ... The grammar of graphics takes us beyond a limited set of charts (words) to an almost unlimited world of graphical forms (statements). 

Thinking about data visualization through the lens of the grammar of graphics allow us to see that graphs typically have data that is plotted on the x axis and other data that is plotted on the y axis. And this is the case no matter whether the type of graph we end up with is, to take just two examples, a bar chart of a line chart. Consider these two graphs:

TODO: Add images of bar chart and line chart showing same data

As an academic statistician, Wilkinson's goal in writing *The Grammar of Graphics* was mostly to provide a novel way of thinking about data visualization. But his feelings on graph-making tools like Excel were clear when he wrote that "most charting packages channel user requests into a rigid array of chart types. To atone for this lack of flexibility, they offer a kit of post-creation editing tools to return the image to what the user originally envisioned."

The answer to the unspoken request for product would come in 2010, when Hadley Wickham announced the `ggplot2` package for R. Implementing Wilkinson's ideas not only to describe graphs, but also to make them, `ggplot2` would go on to revolutionize the world of data visualization. 

## ggplot2

 were very different than those of the office warrior who just wants to produce a report to share with their boss. But Wilkinson did have at least one riposte to 


A theoretical book, *The Grammar of Graphics* is short on practical tips. 

Rather than thinking about, say, a bar chart as a distinct type of chart compared to a line chart, we can recognize that both share certain properties. 



TODO: Think about use of chart, graph, plot, figure etc

