# R is a Full-Fledged Map-Making Tool 

When I first started learning R, I had no idea it could make maps. I thought of R as being designed to work with numbers, not the shapes that make up maps. So I was surprised when I first saw people making maps with R. This is possible, I wondered? 

The answer is yes: you absolutely can make maps in R. And not just prosaic maps. Beautiful maps that use high-quality design principles. Maps that are good enough to be featured in top media outlets. 

When many people hear "maps" they immediately think of ArcGIS. But this tool is expensive, with business licenses for ArcGIS starting at $500 per year. Excel has added support for map-making in recent years, but features are limited (making maps based on street addresses, for example, is not possible). There is QGIS, an open-source tool similar to ArcGIS. But the mental tax that comes from context switching between tools is significant. Learning to make maps in R means you can do everything, for free, in one tool. 

And the best part of making maps in R is that we can use what we learned about high-quality data visualization in \@ref(data-viz-chapter). Maps are a form of data visualization and the principles discussed in that chapter apply here as well. 

Many people assume that making maps requires a ton of specialized knowledge (this is what I used to think). It doesn't. There are a few things you need to know in order to work with geospatial data used to make maps. But once you understand the basics, you too can make high-quality maps in R. 

To show how anyone can make high-quality maps in R, I spoke with Abdoul Madjid. A polyglot developer originally from Benin, Madjid has been making maps with R for several years. In January 2022, he made a beautiful map that shows rates of COVID-19 in the US throughout 2021. 

[TODO: ADD MAP]

Madjid is not a geospatial information systems (GIS) specialist, but he has learned how to work with geospatial data in R in a way that enables him to make beautiful maps like this one. I spoke with Madjid and he explained how he obtained the data, analyzed it, and made his COVID-19 map.

In this chapter, we will begin by diving into geospatial data, giving you the minimum you need to know in order to make maps in R. We'll then walk through Abdoul Madjid's code, looking at the choices he made that resulted in this high-quality map. The chapter concludes with some thoughts on why R is the perfect tool for making maps.


```{r eval = FALSE}
# Load libraries ----------------------------------------------------------
library(tidyverse)

# Data Reading and Wrangling ----------------------------------------------

# NY TIMES Data 
covid_data <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
usa_states <- read_csv("https://raw.githubusercontent.com/AbdoulMa/TidyTuesday/main/2022_w1/usa_states_population.csv") %>% 
  select(State, Pop)

# States Geometries
usa_states_geom <- albersusa::usa_sf() %>% 
  sf::st_transform(albersusa::us_laea_proj) %>%
  select(name)

covid_cases <- covid_data %>% 
  group_by(state, fips) %>% 
  arrange(date) %>% 
  # DON'T USE DIFF - somedays data  are incoherent 
  mutate(
    pd_cases = lag(cases) # Previous Day Cases
  ) %>% 
  replace_na(list(pd_cases = 0)) %>% 
  mutate(
    daily_cases = case_when(cases > pd_cases ~ cases - pd_cases, 
                            TRUE ~ 0)
  ) %>%
  ungroup() %>% 
  arrange(state, date) 

# Roll Mean Computing
covid_cases_rm <- covid_cases %>% 
  mutate(roll_cases = zoo::rollmean(daily_cases, k = 5, fill = NA)) %>% 
  # Select 2021 Data
  filter(lubridate::year(date) == 2021) %>% 
  left_join(usa_states, by = c("state" = "State")) %>% 
  drop_na(Pop) %>% 
  mutate(incidence_rate = 10^5 *roll_cases / Pop) %>% 
  mutate(incidence_rate  = cut(incidence_rate, breaks = c(seq(0,50,5), Inf), include.lowest = T) %>% 
           factor(labels = paste0(">", seq(0,50, 5)))) 


# Graphic -----------------------------------------------------------------
bg_color <- "#e5e4e2"
font_family <- "Times New Roman"
caption <- "Incidence rates are calculated for 100,000 people in each state.
Inspired from a graphic in the DIE ZEIT newspaper of November 18, 2021.
Data from NY Times · Tidytuesday Week-1 2022 · Abdoul ISSA BIDA."

# Plot 
covid_evolution_plot <- usa_states_geom %>% 
  left_join(covid_cases_rm, by = c("name" = "state")) %>% 
  mutate(fancy_date = fct_inorder(format(date, "%b. %d"))) %>% 
  ggplot() + 
  geom_sf(aes(fill = incidence_rate), size = .05, color = "grey55") + 
  facet_wrap(vars(fancy_date), strip.position = "bottom")+ 
  colorspace::scale_fill_discrete_sequential(name = str_to_upper("COVID-19 Incidence Rate"),
                                             palette = "Rocket", rev = T, 
                                             guide = guide_legend(
                                               nrow = 1,
                                               keyheight = unit(.75, "cm"),
                                               keywidth = unit(.75, "cm"),
                                               label.position = "right",
                                               label.theme = element_text(family = font_family, size = rel(15), margin = margin(r = 15)),
                                               title.theme = element_text(family = font_family, size = rel(18),margin = margin(b = .5, unit = "cm")),
                                               title.position = "top",
                                               title.hjust = .5
                                             )) +
  theme_minimal() + 
  theme(
    plot.title = element_text(color = "#111111", family = font_family, size = rel(5), face = "bold", margin = margin(t = .5, b = .5, unit = 'cm'),
                              hjust = 0.5),
    plot.caption = element_text(family = font_family, size = rel(1.25), hjust = .5, face = "bold", margin = margin(t = .25, b = .25, unit = 'cm')),
    plot.margin = margin(t = .5, r= .5, b = .5, l=.5, unit = "cm"),
    legend.box.spacing = unit(.5, "cm"),
    text = element_text(family = font_family, color = "#111111"),
    panel.grid = element_blank(),
    axis.text = element_blank(),
    strip.text = element_text( size = rel(1.125), face = "bold"),
    legend.position = "top",
    legend.text =  element_text(family = font_family),
    plot.background = element_rect(fill = bg_color , color = NA)
  ) +
  labs(title = "2021 · A pandemic year",
       caption = caption)

ggsave(covid_evolution_plot, 
       filename = glue::glue("temp.png"), width = 25, height = 25, device = ragg::agg_png, dpi = 640)

```

