# Access Up to Date Census Data with the `tidycensus` Package 

If you've ever worked with data from the United States Census Bureau, you know what a hassle it can be. The typical process involves going to the Census Bureau website, finding the data you need, downloading it, and then working with it in your data analysis tool of choice. Working with Census Bureau data in this way involves a lot of pointing and clicking, and gets very tedious over time.

That tedium is what drove Texas Christian University geographer Kyle Walker to develop a package to automate the process of bringing Census Bureau data into R. Walker had previously created a package called `tigris` to automatically bring in shape files from the Census Bureau. As he told me, "I was using `tigris` pretty heavily in my own work to bring in the spatial data, but I didn't have a seamless way to get the demographic data as well." Drawing on his experience developing `tigris`, Walker would develop the `tidycensus` package, which allows R users to bring in data from various Census Bureau datasets. With `tidycensus`, a user can write just a few lines of code and get data on, say, the median income in all counties in the United States. 

In this chapter, we'll learn how the `tidycensus` package works. We'll do this using examples from two datasets that `tidyverse` makes it possible to work with: the decennial Census and the American Community Survey. We'll also show how we can use the data from these two sources for additional analysis and to make maps by accessing geospatial and demographic data simultaneously. While this chapter focuses on data from the United States Census Bureau, the conclusion lists other R packages that access analogous data for other countries. And finally, the conclusion highlights some of the reasons why using a package like `tidycensus` can improve your workflow. 