```{r}
i <- 1
chapter_number <- 13
source("_common.R")
```

# Conclusion {#conclusion}

R was invented in 1993 as a tool for statistics. In the years since then, it has been used for plenty of statistical analysis. But over the last three decades, R has also become a tool that can do much more than statistics. 

As you've seen in this book, R is great for making visualizations. You can use it to create high-quality data visualization and maps; make your own theme to keep your visuals consistent and on-brand; and generate tables that look good and communicate well. Using R Markdown or Quarto, you can create reports, presentations, and websites. And best of all, these are all reproducible, meaning that updating them is as easy as rerunning your code. Finally, you've seen that R can help you to automate how you access data as well as assist you in collaborating with others through functions and packages that you make. 

If R was new to you before you started this book, I hope you feel inspired to learn and use it. If you are an experienced R user, I hope this book has shown you ways to use R that you hadn't previously considered. No matter your background, if you were initially attracted to R as a tool for statistics, I hope you are now excited to use R without statistics as well. 