---
title: "Interview with Garrick Aden-Buie and Travis Gerke"
output: html_document
---

# Background

Travis director of data science at the Prostate Cancer Clinical Trials Consortium. Previously, he was a faculty member and health informatics director at Moffett Cancer Center. 

Garrick is a data science educator and R developer at RStudio. He was previously a data scientist at Moffett. 

## How did you each get into R? What benefits did using R offer compared to what you had used previously?

## Garrick, I've heard you call yourself a full-stack R developer. What do you mean by this?

## Travis, I'm less familiar with the nuts and bolts of what you do every day in your work. Can you talk about your work and how R fits into it?

# Background on development of Moffett R package universe

## Explain a bit of the background on what you did at Moffett?

## What were some of the pain points that led you to think about creating a package in the first place?

- In talk, used example of connecting tissue sample to patient data

## What is the value of putting code like this into a package? Why not just have a functions.R file that people can source in? 

## Did writing package get more R buy-in?
- "Number of gradual on ramps"

## You created not just one package, but multiple. Why break your code into multiple packages? What did each package in moffettverse do?

# Code walkthrough

I'd like to create a VERY simple package during our interview. I'm thinking something like making a ggplot theme. Would one of you be willing to do this live? 

Here's what I want to cover (basically Chapter 2 of v2 of R Packages book: https://r-pkgs.org/whole-game.html):

- Creating the package
- Creating a function
- Running check()
- Adding documentation for this function
- Creating a pkgdown site
- Pushing the package to GitHub
- Showing how others can install and use the package

# Reflections on the value of custom packages

## You talked about scaling people. Explain how developing a custom package allows you to do this.

## Your code examples talk about how the code is more comprehensible by humans. Why is this valuable?

## You talk about the value not only of having code in a single place, but also have associated docs through things like pkgdown. Explain why you see this is key to the success of the moffittverse or other custom packages.

## Explain the idea of a happy path.

https://twitter.com/grrrck/status/1468704410045984775

# Wrapping up

## What are the best resources if people want to learn to make their own packages?

## Where can people learn more about you and connect with you? 


# Links

https://slides.garrickadenbuie.com/build-your-own-universe/#1
https://slides.garrickadenbuie.com/build-your-own-universe/part-two.html#1
https://www.youtube.com/watch?v=lm0QYr1C2Sw